module.exports = {
  members: {
    SET_1: [
      // "BlackDev",
      "Yemi",
      // "Sesan",
      "Dro",
      "Bosipo",
      "Yosi",
      "Ifihan",
      "Olamilekan",
      "Sarima",
      "Kromate",
      "Ovbioba",
      "Biola",
      "Dotun",
      "Yin",
      "John Igwe",
      "Uche",
      "Ayeesha",
      "Jimoh",
      "Paul Dumebi"
    ],
    SET_2: [
      "JudeX",
      "Nanya",
      "Samuel",
      "Bosun",
      "Oluwatosin",
      "Favour",
      "Aphomer",
      "Chisombiri",
      "iMyke",
      "Shade",
      // "Philip",
      "Tony",
      "Sunkanmi",
      "Paul",
      "Temmy",
      "Bashorun",
      "Emmanuel Ogunwede",
      "Quyum"
    ],
  },
  REFERENCE_DATE_STRING: "March 06, 2022",
  SEED: "oqiefi1293919qnwkasdasd0s",
};
